In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df_test = pd.read_csv('./Data/airbnb_limpio_final.csv')
df_test.head()

,id,summary,experiences_offered,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,...,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,number_of_reviews_scaled,porcentaje_disponibilidad
0,11508,NaN,none,42762,2009-10-01,"New York, New York, United States",within a few hours,100.0,100.0,t,...,strict_14_with_grace_period,f,f,1,1,0,0,0.27,0.052,1.0
1,12463,My apartment is centrally located in Recoleta ...,none,48799,2009-10-28,"Danbury, Connecticut, United States",within a few hours,100.0,100.0,f,...,moderate,f,f,1,0,1,0,0.16,0.040,1.0
2,13095,Palermo Viejo B&B is a typical home in one of ...,none,50994,2009-11-03,"Buenos Aires, Capital Federal, Argentina",within an hour,100.0,100.0,f,...,strict_14_with_grace_period,f,f,7,0,7,0,0.06,0.002,1.0
3,13096,Palermo Viejo B&B is a typical home in one of ...,none,50994,2009-11-03,"Buenos Aires, Capital Federal, Argentina",within an hour,100.0,100.0,f,...,strict_14_with_grace_period,f,f,7,0,7,0,0.00,0.000,1.0
4,13097,Palermo Viejo B&B is a typical home in one of ...,none,50994,2009-11-03,"Buenos Aires, Capital Federal, Argentina",within an hour,100.0,100.0,f,...,strict_14_with_grace_period,f,f,7,0,7,0,1.89,0.132,1.0

In [ ]:
df_test.describe()

,id,host_id,host_response_rate,host_acceptance_rate,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,...,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,number_of_reviews_scaled,porcentaje_disponibilidad
count,2.144800e+04,2.144800e+04,21448.000000,21448.000000,21445.000000,21445.000000,21448.000000,21448.000000,21448.000000,21448.000000,...,21448.000000,21448.000000,21448.000000,21448.000000,21448.000000,21448.000000,21448.000000,21448.000000,21448.000000,21448.000000
mean,2.691917e+07,1.063946e+08,93.926473,90.493519,6.207927,6.207927,-34.592754,-58.416438,2.625793,1.205497,...,9.850242,9.877797,9.605931,5.782311,4.923443,0.555670,0.100755,0.802205,0.033703,0.571540
std,1.240698e+07,9.958825e+07,19.048043,21.308275,15.016443,15.016443,0.018448,0.029946,1.271995,0.546483,...,0.635551,0.533868,0.850709,14.072275,13.832421,1.739847,0.935692,1.115188,0.065528,0.376042
min,1.150800e+04,2.616000e+03,0.000000,0.000000,0.000000,0.000000,-34.688950,-58.530200,1.000000,0.000000,...,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.837068e+07,1.600092e+07,100.000000,93.000000,1.000000,1.000000,-34.603710,-58.435972,2.000000,1.000000,...,10.000000,10.000000,9.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.243836
50%,3.017719e+07,7.179302e+07,100.000000,100.000000,1.000000,1.000000,-34.592210,-58.415475,2.000000,1.000000,...,10.000000,10.000000,10.000000,1.000000,1.000000,0.000000,0.000000,0.350000,0.008000,0.493151
75%,3.732016e+07,1.855516e+08,100.000000,100.000000,4.000000,4.000000,-34.582167,-58.392590,3.000000,1.000000,...,10.000000,10.000000,10.000000,3.000000,2.000000,0.000000,0.000000,1.130000,0.038000,0.991781
max,4.328111e+07,3.445900e+08,100.000000,100.000000,112.000000,112.000000,-34.534100,-58.356550,16.000000,30.000000,...,10.000000,10.000000,10.000000,99.000000,99.000000,26.000000,19.000000,10.730000,1.000000,1.000000

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21448 entries, 0 to 21447
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            21448 non-null  int64
 1   summary                                       20336 non-null  object
 2   experiences_offered                           21448 non-null  object
 3   host_id                                       21448 non-null  int64
 4   host_since                                    21445 non-null  object
 5   host_location                                 21350 non-null  object
 6   host_response_time                            21448 non-null  object
 7   host_response_rate                            21448 non-null  float64
 8   host_acceptance_rate                          21448 non-null  float64
 9   host_is_superhost                             21445 non-null  object
 10  host_neighbourhood                            18869 non-null  object
 11  host_listings_count                           21445 non-null  float64
 12  host_total_listings_count                     21445 non-null  float64
 13  host_verifications                            21445 non-null  object
 14  host_has_profile_pic                          21445 non-null  object
 15  host_identity_verified                        21445 non-null  object
 16  street                                        21448 non-null  object
 17  neighbourhood                                 21448 non-null  object
 18  neighbourhood_cleansed                        21448 non-null  object
 19  city                                          20911 non-null  object
 20  state                                         21304 non-null  object
 21  zipcode                                       21448 non-null  object
 22  market                                        21428 non-null  object
 23  smart_location                                21448 non-null  object
 24  country_code                                  21448 non-null  object
 25  country                                       21448 non-null  object
 26  latitude                                      21448 non-null  float64
 27  longitude                                     21448 non-null  float64
 28  is_location_exact                             21448 non-null  object
 29  property_type                                 21448 non-null  object
 30  room_type                                     21448 non-null  object
 31  accommodates                                  21448 non-null  int64
 32  bathrooms                                     21448 non-null  float64
 33  bedrooms                                      21448 non-null  float64
 34  beds                                          21448 non-null  float64
 35  bed_type                                      21448 non-null  object
 36  amenities                                     21448 non-null  object
 37  price                                         21448 non-null  float64
 38  security_deposit                              21448 non-null  float64
 39  cleaning_fee                                  21448 non-null  float64
 40  guests_included                               21448 non-null  int64
 41  extra_people                                  21448 non-null  float64
 42  minimum_nights                                21448 non-null  int64
 43  maximum_nights                                21448 non-null  int64
 44  minimum_minimum_nights                        21448 non-null  int64
 45  maximum_minimum_nights                        21448 non-null  int64
 46  minimum_maximum_nights                        21448 non-null  int64
 47  maximum_maximum_nights                        21448 non-null  int64
 48  minimum_nights_avg_ntm                        21448 non-null  float64
 49  maximum_nights_avg_ntm                        21448 non-null  float64
 50  has_availability                              21448 non-null  object
 51  availability_30                               21448 non-null  int64
 52  availability_60                               21448 non-null  int64
 53  availability_90                               21448 non-null  int64
 54  availability_365                              21448 non-null  int64
 55  number_of_reviews                             21448 non-null  int64
 56  number_of_reviews_ltm                         21448 non-null  int64
 57  first_review                                  15957 non-null  object
 58  last_review                                   15957 non-null  object
 59  review_scores_rating                          21448 non-null  float64
 60  review_scores_accuracy                        21448 non-null  float64
 61  review_scores_cleanliness                     21448 non-null  float64
 62  review_scores_checkin                         21448 non-null  float64
 63  review_scores_communication                   21448 non-null  float64
 64  review_scores_location                        21448 non-null  float64
 65  review_scores_value                           21448 non-null  float64
 66  requires_license                              21448 non-null  object
 67  instant_bookable                              21448 non-null  object
 68  is_business_travel_ready                      21448 non-null  object
 69  cancellation_policy                           21448 non-null  object
 70  require_guest_profile_picture                 21448 non-null  object
 71  require_guest_phone_verification              21448 non-null  object
 72  calculated_host_listings_count                21448 non-null  int64
 73  calculated_host_listings_count_entire_homes   21448 non-null  int64
 74  calculated_host_listings_count_private_rooms  21448 non-null  int64
 75  calculated_host_listings_count_shared_rooms   21448 non-null  int64
 76  reviews_per_month                             21448 non-null  float64
 77  number_of_reviews_scaled                      21448 non-null  float64
 78  porcentaje_disponibilidad                     21448 non-null  float64
dtypes: float64(25), int64(20), object(34)
memory usage: 12.9+ MB